---
- name: Set Alias name to account
  environment:
    AWS_ACCESS_KEY_ID: "{{ assumed_role.sts_creds.access_key }}"
    AWS_SECRET_ACCESS_KEY: "{{ assumed_role.sts_creds.secret_key }}"
    AWS_SESSION_TOKEN: "{{ assumed_role.sts_creds.session_token }}"
  command: >-
    {{ aws_cli }} iam create-account-alias
    --account-alias {{ account_name }}{{ alias_suffix }}
  register: _createaccountalias
  failed_when:
    - _createaccountalias.rc != 0
    - '"already exists" not in _createaccountalias.stderr'
  changed_when: '"already exists" not in _createaccountalias.stderr'
  when: not account_altready_exists
