---
- tags:
    - nuke
    - ddns
  when: operation == 'CREATE' or nuke_sandbox | bool
  block:
    - name: Fetch all NS records for this sandbox
      shell: >-
        set -o pipefail;
        host -t ns -W 60 -R 10 {{ account_name }}.{{ ddns_domain }}
        | awk '{ print $4 }'
      register: _recordfind
      ignore_errors: true

    - when: _recordfind is succeeded
      set_fact:
        ddns_ns_records: "{{ _recordfind.stdout.split('\n') }}"

    - when: _recordfind is failed
      set_fact:
        ddns_ns_records: ""

    - name: Override NS records to DDNS
      community.general.nsupdate:
        server: "{{ lookup('dig', ddns_server) }}"
        zone: "{{ ddns_domain }}."
        record: "{{ account_name }}.{{ ddns_domain }}."
        value: "{{ ns_records }}"
        type: NS
        port: "{{ ddns_port | d('53') }}"
        key_name: "{{ ddns_key_name }}"
        key_algorithm: "{{ ddns_key_algorithm | d('hmac-sha512') }}"
        key_secret: "{{ ddns_key_secret }}"
        state: present
