---
- name: Create IAM role using Cloudformation
  cloudformation:
    profile: "{{ account_profile }}"
    template_body: "{{ lookup('file', 'CF-IAM.json') }}"
    region: "{{ aws_region }}"
    stack_name: roles
    on_create_failure: DO_NOTHING
  register: _cfiamrole
  until: _cfiamrole is succeeded
  delay: 60
  retries: 5
