---
- import_tasks: pre_checks.yml
- import_tasks: account.yml
  tags: account
- import_tasks: profile.yml
  tags: profile
- import_tasks: assume.yml
- import_tasks: iam.yml
- import_tasks: alias.yml
- include_tasks: ou.yml
  when:
    - account_destination_ou is defined
    - operation == 'CREATE'
  tags: ou
- include_tasks: regions.yml
- include_tasks: reset.yml
  when: operation == 'RESET'
- import_tasks: user.yml
- import_tasks: route53.yml
  tags: route53
- include_tasks: keypair.yml
  when: operation in ['CREATE', 'RESET']
  tags: keypair
- import_tasks: pool.yml
