---
- name: Create output_dir
  file:
    path: "{{ output_dir }}"
    state: directory


- name: Ensure vault file exists
  stat:
    path: "{{ vault_file }}"
  register: r_path

- assert:
    that: r_path.stat.exists
    msg: "{{ vault_file }} doesn't exist, please create it"

- include_tasks: test_ipa.yml
  tags: ipa
  when:
    - kerberos_user is defined
    - kerberos_password is defined or kerberos_keytab is defined
