---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/version: {{ .Values.deployment.tag | default .Chart.AppVersion | quote }}
    meta.helm.sh/release-name: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
    {{- if .Values.labels }}
    {{- toYaml .Values.labels | nindent 4 }}
    {{- end }}
