== Create new AWS sandboxes ==

This is a manual process and require caution and validation.

WARNING: make sure the range you're creating is available: check the prod DB but also the DEV DB
----
# latest sandboxes, prod
sandbox-list -all --sort name |tail

# latest sandboxes, dev
(export AWS_PROFILE=dev; export dynamodb_table=accounts-dev;  sandbox-list -all --sort name | tail)
----

.on admin host
----
[opentlc-mgr@admin (PROD) ~]$ . ~/pool_management/python_virtualenv/bin/activate
(python_virtualenv) [opentlc-mgr@admin (PROD) ~]$ cd pool_management/sandbox/playbooks

# .create 10 AWS sandbox accounts: sandbox3001 .. sandbox3010
# You can use 'IPA opentlc.com hostadmin for conan' for the kerberos creds
./create_range.yml -e account_num_start=3001 -e account_count=10 -e kerberos_user=... -e kerberos_password=...

# Add GOLD IMAGES to the new accounts
# Generate the list of new sandboxes

sandbox-list --sort name -all |awk '/^sandbox3001 /{flag=1}flag{print $1 " " $3}' > new_sandboxes.txt

# SSH to QA or a place where node is installed, copy new_sandboxes-txt there
# Run cloud-automation to subscribe to GOLD images, see cloud-automation readme

# Go back on admin host, ensure they are all valide
./validate.yml -e account_num_start=3001 -e account_num_end=3010

# user sandbox_enable.sh  to enable the new sandboxes
for i in $(seq 3001 3010); do  sandbox_enable.sh $i; done
----

=== Create new sandboxes for a specific reservation and OU ===

WARNING: This should be done only when strictly necessary. Prefer the regular process of creating/scaling a reservation using existing sandboxes from the available pool instead, see link:../tools/readme.adoc[tools/readme.adoc]

. First, Make sure the reservation already exists in the DB, see link:../tools/readme.adoc[tools/readme.adoc]
+
----
[opentlc-mgr@admin (PROD) ~]$ . ~/pool_management/python_virtualenv/bin/activate
(python_virtualenv) [opentlc-mgr@admin (PROD) ~]$ cd pool_management/sandbox/playbooks

START=3200
COUNT=10
END=3210
RESERVATION=rosa-test

# .create 10 AWS sandbox accounts: sandbox$START .. sandbox$END
./create_range.yml -e account_num_start=$START -e account_count=$COUNT -e sandbox_reservation=$RESERVATION -e account_destination_ou=rosa

# Add GOLD IMAGES to the new accounts
# Generate the list of new sandboxes

sandbox-list --sort name -all |awk '/^sandbox'$START' /{flag=1}flag{print $1 " " $3}' > new_sandboxes.txt

# SSH to QA or a place where node is installed, copy new_sandboxes.txt there
# Run cloud-automation to subscribe to GOLD images, see cloud-automation readme

# Go back on admin host, ensure they are all valide
./validate.yml -e account_num_start=$START -e account_num_end=$END

# If all goes well, enable the sandboxes
for i in $(seq $START $END); do
  sandbox_enable.sh sandbox$i
done

# check the new number of sandboxes in the reservation
sandbox-list --all --reservation $RESERVATION
sandbox-list --all --no-headers --reservation $RESERVATION | wc -l
----
. Manually update the count in the `reservations` to match the number of sandboxes in the reservation.
+
.Increase the count to match the actual number, replace `CHANGE_ME`
[source,sql]
----
update reservation set request = jsonb_set(request, '{resources, 0, count}',to_jsonb(CHANGE_ME)) where reservation_name='rosa-test';
----
