apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- toYaml .Values.labels | nindent 4 }}
spec:
  replicas: 2
  selector:
    matchLabels:
      {{- toYaml .Values.labels | nindent 6 }}
  strategy:
    type: {{ .Values.deployment.strategy }}
  template:
    metadata:
      labels:
        {{- toYaml .Values.labels | nindent 8 }}
    spec:
      containers:
      - name: sandbox-api
        image: {{ .Values.deployment.image }}:{{ .Values.image_tag | default .Values.deployment.tag }}
        imagePullPolicy: {{ .Values.deployment.pullPolicy }}
        livenessProbe:
          initialDelaySeconds: 10
          tcpSocket:
            port: 8080
          timeoutSeconds: 1
        ports:
        - containerPort: 8080
        env:
        ##########################################
        # Postgres
        ##########################################
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: sandbox-api-db
              key: database_url
        ##########################################
        # TOKENS
        ##########################################
        - name: JWT_AUTH_SECRET
          valueFrom:
            secretKeyRef:
              name: sandbox-api-auth
              key: jwt_auth_secret

        ##########################################
        # DYNAMODB
        ##########################################
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: sandbox-api-db
              key: dynamodb_aws_access_key_id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: sandbox-api-db
              key: dynamodb_aws_secret_access_key
        - name: AWS_REGION
          value: {{ .Values.dynamodb_region }}
        - name: dynamodb_table
          value: {{ .Values.dynamodb_table }}
