{{- if .Values.sandbox_api_secrets.database -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: sandbox-api-db
  namespace: {{ .Values.namespace }}
  labels:
    {{- toYaml .Values.labels | nindent 4 }}
data:
  database_url: {{ .Values.sandbox_api_secrets.database.url | b64enc }}
  dynamodb_aws_access_key_id: {{ .Values.sandbox_api_secrets.datase.dynamodb_aws_access_key_id }}
  dynamodb_aws_secret_access_key: {{ .Values.sandbox_api_secrets.datase.dynamodb_aws_secret_access_key }}
{{- end }}

{{- if .Values.sandbox_api_secrets.auth -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: sandbox-api-auth
  namespace: {{ .Values.namespace }}
  labels:
    {{- toYaml .Values.labels | nindent 4 }}
data:
  jwt_auth_secret: {{ .Values.sandbox_api_secrets.auth.jwt_auth_secret | b64enc }}
{{- end }}
