---
apiVersion: v1
kind: Secret
metadata:
  name: sandbox-api-db
  namespace: {{ .Values.namespace }}
  labels:
    {{- toYaml .Values.labels | nindent 4 }}
data:
  database_url: {{ .Values.sandbox_api_secrets.database.url | b64enc }}
  dynamodb_aws_access_key_id: {{ .Values.sandbox_api_secrets.database.dynamodb_aws_access_key_id | b64enc }}
  dynamodb_aws_secret_access_key: {{ .Values.sandbox_api_secrets.database.dynamodb_aws_secret_access_key | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: sandbox-api-auth
  namespace: {{ .Values.namespace }}
  labels:
    {{- toYaml .Values.labels | nindent 4 }}
data:
  jwt_auth_secret: {{ .Values.sandbox_api_secrets.auth.jwt_auth_secret | b64enc }}

---
apiVersion: v1
kind: Secret
metadata:
  name: sandbox-api-vault
  namespace: {{ .Values.namespace }}
  labels:
    {{- toYaml .Values.labels | nindent 4 }}
data:
  vault_secret: {{ .Values.sandbox_api_secrets.vault.vault_secret | b64enc }}
