---
name: build-push
on:
  workflow_call:
    inputs:
      tag:
        description: 'Tag'
        default: 'github-latest'
        required: true
        type: string
      image:
        description: Image
        type: string
        default: api
      labels:
        description: 'quay labels'
        default: ''
        required: false
        type: string

    secrets:
      registry_username:
        description: 'Username to login to Quay.io'
        required: true
      registry_password:
        description: 'password to login to Quay.io'
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-python@v4

      - name: Buildah Action
        uses: redhat-actions/buildah-build@v2
        id: build-image
        with:
          image: sandbox-${{inputs.image}}
          tags: ${{inputs.tag}} ${{ github.sha }}
          labels: ${{ inputs.labels }}
          containerfiles: |-
            Containerfile.${{inputs.image}}

      -  name: Push To quay.io
         id: push-to-quay
         uses: redhat-actions/push-to-registry@v2
         with:
           image: ${{ steps.build-image.outputs.image }}
           tags: ${{ steps.build-image.outputs.tags }}
           registry: quay.io/rhpds
           username: ${{ secrets.registry_username }}
           password: ${{ secrets.registry_password }}
